# FILE: config/optimized_params.yaml
# STRATEGY IMPLEMENTATION GUIDE
# 1. Existing strategies keep their original interfaces with tuned parameters
# 2. New strategies require the following implementation:

"""
# STRATEGY TEMPLATE FOR NEW APPROACHES
class ScalpingStrategy(Strategy):
    params = (
        ('ema_fast', 5),
        ('ema_slow', 21),
        ('rsi_period', 7),
        ('volume_spike_multiplier', 1.5),
        ('min_liquidity', 1000000)
    )
    
    def __init__(self):
        self.ema_fast = ta.EMA(self.data.Close, period=self.p.ema_fast)
        self.ema_slow = ta.EMA(self.data.Close, period=self.p.ema_slow)
        self.rsi = ta.RSI(self.data.Close, period=self.p.rsi_period)
        self.volume_ma = ta.SMA(self.data.Volume, period=20)
        
    def next(self):
        if self.p.min_liquidity > self.data.Volume[-1]:
            return
            
        long_signal = (
            self.ema_fast[-1] > self.ema_slow[-1] and
            self.rsi[-1] < 70 and # Example RSI threshold for long entry
            self.data.Volume[-1] > self.p.volume_spike_multiplier * self.volume_ma[-1]
        )
        
        if long_signal:
            self.buy()
""" # NOTE: Corrected the template to use self.data.Close and self.data.Volume as per standard backtrader convention. Added an RSI threshold example.

# OPTIMIZED PARAMETER GRID
BTCUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9]
    slow_period: [21, 34]
    stop_loss_pct: [0.015]
    take_profit_pct: [0.025]
    ma_type: ["EMA"]
    trend_filter_period: [75]
    time_window: ["08:00-20:00"]

  ScalpingStrategy:
    ema_fast: [5, 7]
    ema_slow: [15, 21]
    rsi_period: [7]
    volume_spike_multiplier: [1.5]
    min_liquidity: [1000000]

ETHUSDT:
  BollingerBandReversionStrategy:
    bb_period: [15]
    bb_std_dev: [1.8]
    stop_loss_pct: [0.018]
    take_profit_pct: [0.03]
    liquidity_threshold: [500000]

  MomentumStrategy:
    atr_period: [10]
    volume_multiplier: [2.0]
    volatility_threshold: [1.5]

XRPUSDT:
  MeanReversionStrategy:
    z_score_period: [20]
    rsi_period: [5]
    profit_target: [0.015]
    max_holding_period: [45]

SUIUSDT:
  BreakoutStrategy:
    consolidation_bars: [12]
    volume_spike: [3.0]
    min_volatility: [0.02]

SOLUSDT:
  HybridStrategy:
    ema_fast: [7]
    ema_slow: [21]
    macd_fast: [5]
    macd_slow: [13]
    macd_signal: [4]

filters:
  apply_seasonality: true
  seasonality_window: ["08:00-20:00 UTC"]
  liquidity_requirements:
    BTC: 1000000
    ETH: 500000  
    XRP: 250000
    SUI: 100000
  risk_parameters:
    max_trades_per_session: 35
    acceptable_slippage: [0.1, 0.25] # Represented as percentage points e.g., 0.1% 