# Example Parameter Grids for Optimization
# Define ranges per symbol and strategy class name

BTCUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]  # Centered around 20
    bb_std_dev: [1.8, 2.0, 2.2] # Centered around 2.0
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    # Parameters translated by optimize.py into return_thresh and volume_thresh tuples
    rsi_threshold_low: [40, 45, 50] # Represents return_thresh[0]
    rsi_threshold_high: [50, 55, 60] # Represents return_thresh[1]
    volume_z_thresh_low: [-3.0, -2.5, -2.0] # Represents volume_thresh[0]
    volume_z_thresh_high: [2.0, 2.5, 3.0] # Represents volume_thresh[1]
    # Risk/Filter parameters
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

XRPUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [9, 15, 20]
    slow_period: [25, 50, 75]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

ALGOUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 10]
    slow_period: [20, 30, 40]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

ETHUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

HBARUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

ADAUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

SOLUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

LTCUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

SUIUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 100, 150, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 100, 150, 200]
  LongShortStrategy:
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 100, 150, 200]

# Add configurations for other symbols as needed
# Note: Renamed keys in LongShortStrategy section to reflect actual expected params
#       (rsi_threshold_low/high, volume_z_thresh_low/high)
#       Removed unnecessary placeholders for EMA/RSI periods for LongShortStrategy. 