# Example Parameter Grids for Optimization
# Define ranges per symbol and strategy class name

BTCUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [14, 18, 21]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [25, 28, 30]
    bb_std_dev: [2.0, 2.2, 2.5]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 150, 175, 200]
  LongShortStrategy:
    return_thresh_low: [-0.0005, -0.0003, -0.0001]
    return_thresh_high: [0.0001, 0.0003, 0.0005]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

XRPUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [8, 10, 12]
    slow_period: [30, 34, 40]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [0.01, 0.015, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [10, 14, 18]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [20, 25, 30]
    bb_std_dev: [2.0, 2.2, 2.5]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [0.015, 0.02, 0.025, 0.03]
    trend_filter_period: [None, 150, 175, 200]
  LongShortStrategy:
    return_thresh_low: [-0.005, -0.003, -0.001]
    return_thresh_high: [0.001, 0.003, 0.005]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

ALGOUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 8, 10]
    slow_period: [20, 25, 30]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 9, 10]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [20, 25, 30]
    bb_std_dev: [2.0, 2.2, 2.5]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 150, 175, 200]
  LongShortStrategy:
    return_thresh_low: [-0.005, -0.003, -0.001]
    return_thresh_high: [0.001, 0.003, 0.005]
    volume_z_thresh_low: [-3.0, -2.5]
    volume_z_thresh_high: [2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

ETHUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [8, 10, 12]
    slow_period: [40, 50, 60]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [14, 18, 21]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [25, 28, 30]
    bb_std_dev: [2.0, 2.2, 2.5]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 150, 175, 200]
  LongShortStrategy:
    return_thresh_low: [-0.0005, -0.0003, -0.0001]
    return_thresh_high: [0.0001, 0.0003, 0.0005]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

HBARUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [100, 125, 150]
  LongShortStrategy:
    return_thresh_low: [-0.005, -0.003, -0.001]
    return_thresh_high: [0.001, 0.003, 0.005]
    volume_z_thresh_low: [-3.0, -2.5]
    volume_z_thresh_high: [2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

ADAUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [10, 14, 18]
    oversold_threshold: [25, 28, 30]
    overbought_threshold: [75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [20, 25, 30]
    bb_std_dev: [2.0, 2.2, 2.5]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [0.015, 0.02, 0.025, 0.03]
    trend_filter_period: [None, 150, 175, 200]
  LongShortStrategy:
    return_thresh_low: [-0.005, -0.003, -0.001]
    return_thresh_high: [0.001, 0.003, 0.005]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

SOLUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13]
    slow_period: [20, 34, 50]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [0.01, 0.015, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 9, 10]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [15, 18, 20, 22, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [0.03, 0.035, 0.04]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 150, 175, 200]
  LongShortStrategy:
    return_thresh_low: [-0.005, -0.003, -0.001]
    return_thresh_high: [0.001, 0.003, 0.005]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

LTCUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [0.04, 0.05, 0.06]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [10, 12, 14]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [20, 25, 30]
    bb_std_dev: [2.0, 2.2, 2.5]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [None, 150, 175, 200]
  LongShortStrategy:
    return_thresh_low: [-0.005, -0.003, -0.001]
    return_thresh_high: [0.001, 0.003, 0.005]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

SUIUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [8, 10, 12]
    slow_period: [40, 50, 60]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
    trend_filter_period: [None, 150, 175, 200]
  RsiMeanReversionStrategy:
    rsi_period: [7, 9, 10]
    oversold_threshold: [15, 20, 25, 30]
    overbought_threshold: [70, 75, 80, 85]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [50, 75, 100]
  BollingerBandReversionStrategy:
    bb_period: [14, 17, 20]
    bb_std_dev: [1.8, 2.0, 2.2, 2.5]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    trend_filter_period: [100, 125, 150]
  LongShortStrategy:
    return_thresh_low: [-0.005, -0.003, -0.001]
    return_thresh_high: [0.001, 0.003, 0.005]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    trend_filter_period: [None, 150, 175, 200]

# --- Universal Parameters (applied if not symbol-specific) ---
# These are harder to represent directly in the grid per symbol/strategy.
# Suggestion: Handle these in the strategy logic or backtester setup.
# - ATR Threshold Filter (e.g., 1.5x 14-day ATR)
# - Seasonality Adjustments (e.g., trading hours 05:00-17:00 UTC for SOL/SUI)
# - Walk-Forward Optimization (Backtester setting)
# - Use EMA instead of SMA (Strategy logic change)
# - Dynamic Beta Hedging (LongShortStrategy logic change)
# - ATR-Adjusted RSI thresholds (RsiMeanReversionStrategy logic change)
# - Z-score return thresholds (LongShortStrategy logic change)

# Note: Some parameter names in LongShortStrategy might need adjustment
# if the optimization script expects different keys for Z-score/beta.
# E.g., 'rsi_threshold_low' might become 'return_z_score_low' or similar.
# Placeholder values used for return_thresh_low/high where Z-score is suggested. 