# Example Parameter Grids for Optimization
# Define ranges per symbol and strategy class name

BTCUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
    # exit_threshold: [45, 50, 55] # Example: Add exit condition if strategy uses it
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]  # Centered around 20
    bb_std_dev: [1.8, 2.0, 2.2] # Centered around 2.0
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
    # entry_threshold: [0.05, 0.1] # Example: Add if strategy needs specific entry distance
    # exit_threshold: [0.5, 0.6] # Example: Add if strategy needs specific exit distance
  LongShortStrategy:
    fast_ema_period: [9, 12, 15] # Common short EMAs
    slow_ema_period: [21, 26, 30] # Common longer EMAs
    rsi_period: [10, 14, 21] # Standard RSI periods
    rsi_threshold_low: [40, 45, 50] # RSI levels for trend/momentum filter
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0] # Z-score thresholds for volume
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

XRPUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [9, 15, 20] # Example different range
    slow_period: [25, 50, 75]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

ALGOUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 10]
    slow_period: [20, 30, 40]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

ETHUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

HBARUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

ADAUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

SOLUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

LTCUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

SUIUSDT:
  MovingAverageCrossoverStrategy:
    fast_period: [5, 9, 13, 21]
    slow_period: [21, 34, 50, 100]
    stop_loss_pct: [None, 0.02, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.06, 0.10]
    trailing_stop_loss_pct: [None, 0.01, 0.02]
  RsiMeanReversionStrategy:
    rsi_period: [7, 10, 14, 21]
    oversold_threshold: [20, 25, 30]
    overbought_threshold: [70, 75, 80]
    stop_loss_pct: [None, 0.02, 0.04]
    take_profit_pct: [None, 0.03, 0.05, 0.08]
    trailing_stop_loss_pct: [None, 0.015, 0.025]
  BollingerBandReversionStrategy:
    bb_period: [15, 20, 25]
    bb_std_dev: [1.8, 2.0, 2.2]
    stop_loss_pct: [None, 0.03, 0.05]
    take_profit_pct: [None, 0.04, 0.07, 0.10]
    trailing_stop_loss_pct: [None, 0.02, 0.03]
  LongShortStrategy:
    fast_ema_period: [9, 12, 15]
    slow_ema_period: [21, 26, 30]
    rsi_period: [10, 14, 21]
    rsi_threshold_low: [40, 45, 50]
    rsi_threshold_high: [50, 55, 60]
    volume_z_thresh_low: [-3.0, -2.5, -2.0]
    volume_z_thresh_high: [2.0, 2.5, 3.0]
    stop_loss_pct: [None, 0.02, 0.035]
    take_profit_pct: [None, 0.05, 0.075, 0.10]
    trailing_stop_loss_pct: [None, 0.015, 0.025]

# Add configurations for other symbols as needed
# Note: Removed return_thresh_low/high from LongShortStrategy as they are not standard params
#       Replaced volume_thresh_low/high with volume_z_thresh_low/high based on strategy implementation using z-scores.
#       Added typical EMA and RSI params often used in combined strategies.
#       Added commented-out examples for entry/exit thresholds in RSI and BB strategies if needed later. 