# Runtime configuration for the trading bot
# Modify this file while the trader.py script is running to change behavior.

# Target trading symbol (must match the running bot's symbol)
symbol: XRPUSDT 

# Name of the strategy class to use (must match class name in strategies/)
strategy_name: RsiMeanReversionStrategy

# Parameters for the selected strategy
# These must match the __init__ arguments of the strategy class.
strategy_params:
  # Updated parameters for LongShortStrategy (BTCUSDT) from best_params.yaml
  # return_thresh_high: 0.0001
  # return_thresh_low: -0.0005
  # volume_thresh_high: 3
  # volume_thresh_low: -3
  
  # --- Example for MACross (if strategy_name was MovingAverageCrossoverStrategy) ---
  # fast_period: 9
  # slow_period: 21
  
  # --- Example for RSIReversion ---
  # rsi_period: 14
  # oversold_threshold: 30
  # overbought_threshold: 70
  
  # --- Example for BBReversion ---
  # bb_period: 20
  # bb_std_dev: 2.0

  # --- Example for RsiMeanReversionStrategy (XRPUSDT from best_params.yaml) ---
  # strategy_name: RsiMeanReversionStrategy # Don't forget to change strategy_name above if using this!
  # symbol: XRPUSDT # Don't forget to change symbol above!
  # --- RsiMeanReversionStrategy Params: ---
  overbought_threshold: 75
  oversold_threshold: 20
  rsi_period: 10
  stop_loss_pct: 0.02
  take_profit_pct: null # or leave blank if not used
  trailing_stop_loss_pct: 0.015
  trend_filter_period: 150

# --- Optional: Add other runtime tunable parameters below ---
# e.g., trade_units: 0.002
# e.g., max_trades: 10

# Trading Units (overrides the initial --units argument)
# units: 0.001

# Stop Loss Percentage (e.g., 0.02 for 2%)
# stop_loss_pct: 0.02

# Apply ATR Filter (true/false)
# apply_atr_filter: false 